### ISSUE TITLE
Errors importing PQFCustomLoaders both Objective-C & Swift

### ISSUE THREAD

**Issue by dfreniche** [poolqf/PQFCustomLoaders#3]
Using CocoaPods 0.37.0, Xcode 6.3.1, OS X 10.10.3

When I create a test project, both using Swift / Objective C with the same Podile:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target :'Test' do
    pod 'PQFCustomLoaders'   
end

```

I find errors while importing PQFCustomLoaders. 
- In the Objective-C project:

> 'UIColor+FlatColors.h' file not found with <angled> include; use "quotes" instead
- In the Swift One:

> /Users/dfreniche/Desktop/test_pol/swift/Test/Pods/PQFCustomLoaders/PQFCustomLoaders/PQFCustomLoaders.h:12:9: 'UIColor+FlatColors.h' file not found

It's all related to the FlatColors category you're importing, that's not found inside the Pods project folder structure. Changing that import to:

```
#import <UIColor_FlatColors/UIColor+FlatColors.h>
```

Solves all problems

**Comment by polqf** [comment]
@dfreniche Fixed on the new version https://github.com/poolqf/PQFCustomLoaders/releases/tag/1.0.1.
Thanks for the heads up! 😄
