### ISSUE TITLE
No working when using in Swift Project

### ISSUE THREAD

**Issue by antonio081014** [poolqf/PQFCustomLoaders#9]
Everything works fine in Objc project, but when I tried to add it to my Swift project, 

```
use_frameworks!
pod 'PQFCustomLoaders'
```

It shows 
![screen shot 2016-10-28 at 11 30 48](https://cloud.githubusercontent.com/assets/777705/19817800/06c65056-9d02-11e6-9bc1-11062388487c.png)

**Comment by polqf** [comment]
Hi @antonio081014 , I've fixed the issue with UIColors+FlatColors here: https://github.com/poolqf/PQFCustomLoaders/commit/bfbf6a7b560db89da480a1e9e4d3a4fa66cec300

The thing is that although you can install PQFCustomLoaders, it is not usable. Tbh I've not invested more than 30 min, but seems that to make it work in Swift it needs a little bit of work
